services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    networks:
      - "{{ traefik_network }}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /opt/portainer/data:/data
    labels:
      "traefik.enable=true"

      # Router for HTTPS
      - "traefik.http.routers.portainer.rule=Host(`portainer.pearsalls.online`)"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.routers.portainer.tls.certresolver=cf"

      # Service definition
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"

networks:
  {{ traefik_network }}:
    external: true
