---
- name: Ensure Traefik network exists
  community.docker.docker_network:
    name: "{{ traefik_network }}"
    state: present

- name: Create Traefik directory
  file:
    path: /opt/traefik
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Deploy traefik.yml
  template:
    src: traefik.yml.j2
    dest: /opt/traefik/traefik.yml
    owner: root
    group: root
    mode: "0644"

- name: Deploy dynamic.yml
  template:
    src: dynamic.yml.j2
    dest: /opt/traefik/dynamic.yml
    owner: root
    group: root
    mode: "0644"

- name: Deploy docker-compose.yml
  template:
    src: docker-compose-traefik.yml.j2
    dest: /opt/traefik/docker-compose.yml
    owner: root
    group: root
    mode: "0644"

- name: Ensure Traefik acme directory exists
  file:
    path: /etc/traefik
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Ensure acme.json exists
  file:
    path: "{{ traefik_acme_storage }}"
    state: touch
    owner: root
    group: root
    mode: "0600"

- name: Start Traefik with Docker Compose
  command: docker compose up -d
  args:
    chdir: /opt/traefik
