---
- name: Ensure proxy network exists
  community.docker.docker_network:
    name: proxy
    driver: bridge
    state: present

- name: Ensure Traefik config directory exists
  file:
    path: /opt/traefik
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Deploy static Traefik config
  template:
    src: traefik.yml.j2
    dest: /opt/traefik/traefik.yml
    owner: root
    group: root
    mode: '0644'

- name: Deploy dynamic Traefik config
  template:
    src: dynamic.yml.j2
    dest: /opt/traefik/dynamic.yml
    owner: root
    group: root
    mode: '0644'

- name: Ensure acme.json exists with correct permissions
  file:
    path: /opt/traefik/acme.json
    state: touch
    owner: root
    group: root
    mode: '0600'

- name: Deploy Traefik container
  community.docker.docker_container:
    name: traefik
    image: traefik:v3.6.1
    pull: true
    state: started
    restart_policy: unless-stopped
    recreate: true
    force_kill: true
    user: "0:0"

    command:
      - --configFile=/etc/traefik/traefik.yml
      - --providers.docker=true

    networks_cli_compatible: true
    networks:
      - name: proxy

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - /opt/traefik/dynamic.yml:/etc/traefik/dynamic.yml:ro
      - /opt/traefik/acme.json:/acme.json
