# Global variables
docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin

# Traefik variables
traefik_email: rpearsall1982@gmail.com
traefik_acme_storage: /etc/traefik/acme.json
traefik_env_file: /etc/traefik/cloudflare.env
network_frontend: frontend
network_backend: backend
traefik_domain: pearsalls.online

# Cloudflared variables
cloudflared_tunnel_name: hanta-web
cloudflared_config_dir: /etc/cloudflared

cloudflared_ingress:
  - hostname: portainer.pearsalls.online
    service: https://traefik:443
  - hostname: traefik.pearsalls.online
    service: https://traefik:443
