# playbooks/test.yml
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Load vault variables
      include_vars:
        file: ../inventories/group_vars/vault.yml

    - name: Debug vault_cloudflare_api_token
      debug:
        var: vault_cloudflare_api_token

